runner:
  plugin: threaded
  options:
    num_workers: 20  # Default is 20 if not specified

inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventory/hosts.yaml"
    group_file: "inventory/groups.yaml"
    defaults_file: "inventory/defaults.yaml"