sandbox-iosxr-1:
  hostname: sandbox-iosxr-1.cisco.com
  platform: cisco_xr
  groups:
    - netmiko_group
  connection_options:
    netmiko:
      extras:
        device_type: cisco_xr
        username: admin
        password: C1sco12345

sbx-nxos-mgmt:
  hostname: sbx-nxos-mgmt.cisco.com
  platform: cisco_nxos
  groups:
    - netmiko_group
  connection_options:
    netmiko:
      extras:
        device_type: cisco_nxos
        username: admin
        password: Admin_1234!
